apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7vVmq+FxGRhyujPLL5h4cFPLIqJ1R7cbQMH7n3Cuow6hnbg2Z5rQ7Q==,iv:kKGR11hMnCAmTZEbyJR7aEudUsVCVfPAV3w4F3KdqHI=,tag:C6mdnTMpKzHBz0IskiewpA==,type:str]
sops:
  age:
    - recipient: age1dc9236rsea7k8gtqttxfr832cz3s5k6rx37cqvuxe0432ud22yqsf9mhqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVXRlb0YwTStzbUozRUc4
        dVYvcWxPSkszU0JoS0RqaTAzS3g4WnBzRFNvCm84aXFyTTRlRUhUZEg0dHdFMUtk
        THZKMHRzcXBNakhvKytwWFhkSVhrTTAKLS0tICs3V3JiaEJHaDBnaWxvcWtjUGxx
        eG5BY3pDTDY0ZVdJNnhpdDZiMkVIbXMKJHxxl+dRMf8o2L5ZtOXqo+IGgY81lijp
        2IQg2ewAKq+gXgnlyTA/SiDL1vK4Z+xkkwnb3+vgu9zvRdNfsu94QQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:19:56Z"
  mac: ENC[AES256_GCM,data:e8tvx1aQNyvTTnaqPf+bgtdckmyof77cCRArFkN9GHSY9Ag2nViRHdwAxKjgvxZWpmmd4g9peKmUZhHR2CpSQB5vGmG593aiDL4MGX90YMCF5TNdI/0j1gezOz5g5dxYqhHE9+pPkRDHqjQ+xMFJVltQ7IFpjfsJwnBg0MTJTXA=,iv:Aq9nGG1V2MQuUtOvIQnShYvJ9lRlJ7ZdJ/uB8Uq343A=,tag:tLyxsBYJ11c1h4VGALKMDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
