---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync-secret"
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=openebs-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=5Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=truenas-nvmeof}"
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:=5Gi}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=truenas-nvmeof-snap}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1001}
      runAsGroup: ${VOLSYNC_PGID:=1001}
      fsGroup: ${VOLSYNC_PGID:=1001}
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
