---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: userinit-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: crunchy-userinit-controller
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: crunchy-userinit
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: database
  values:
    fullnameOverride: crunchy-userinit-controller
