---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-meilisearch-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-meilisearch-volsync-secret
    template:
      data:
        RESTIC_REPOSITORY: "s3:https://nas.kbcb.tansanrao.net:9000/volsync/karakeep-meilisearch"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: volsync-minio-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: karakeep-meilisearch
spec:
  sourcePVC: karakeep-meilisearch
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 14
    repository: karakeep-meilisearch-volsync-secret
    cacheCapacity: 5Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: openebs-hostpath
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      hourly: 24
      daily: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-meilisearch-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    repository: karakeep-meilisearch-volsync-secret
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 5Gi
    storageClassName: openebs-hostpath
    accessModes: ["ReadWriteOnce"]
    capacity: 15Gi
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
