---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/database/crunchy-postgres/operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &userinit crunchy-userinit-controller
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *userinit
  dependsOn:
    - name: crunchy-pgo
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/crunchy-postgres/userinit-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &clusters crunchy-pgo-clusters
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *clusters
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: crunchy-pgo
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/crunchy-postgres/clusters/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &store crunchy-pgo-clustersecretstore
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *store
  dependsOn:
    - name: crunchy-pgo-clusters
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/crunchy-postgres/clustersecretstore/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
