apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XPy9WLEosdmK6qFEtENAXMGtC0MJXcBZwVpCTrHXscQ=,iv:9klZmiaAA1qFogu0B1suBID0F17iChtQlhgfg3ed0Rw=,tag:Fia/DCSEFfwCeGzadIGdeg==,type:str]
sops:
  age:
    - recipient: age1dc9236rsea7k8gtqttxfr832cz3s5k6rx37cqvuxe0432ud22yqsf9mhqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcUJyR0h5UlpZaTB6Z2xC
        SEJDRWNpeklaRy9ocG53Myt6OUxScXlTekRFCnVoclN0czZRSHhzMWU4Z0MzTEc1
        cGZCenNBSms1ZU9BOEhibUJLaTdjZnMKLS0tIGZncDRTMHphQWtXcjV1eS9zRU1y
        R0FYUXRVMGc4WUFOaU1mUUVmOXlESGMK1UGSgT+1nH38fHyMjdv/MFOCPAAfz914
        8fMhZhAs2Sav4VZdVvoUA0VStm3byLaaf8I3w1FuRKyHKqlnCIIHlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:19:56Z"
  mac: ENC[AES256_GCM,data:MNTupOlJu1od866e3mcQl1JcsLzYQWv6T5ii92bHUDsKn7G6nFSI4IiQvSlRzh1gaSYcwZlBO7d6BFbJx3xrbsan+TyM13z6LtMek90dtOidIq8KX0Nsn7K+zoWmVzF3eoewro6lSO1/gCxGKU6QdOcUZiHToeZBz1ogQaeJdMM=,iv:cOlxISRuV8RU/xi6bE7dayci8F7skEt9PprT+ZHLZec=,tag:jW+hXca4dQA39uk+Edx6EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
