---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nvmeof
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 1h
  values:
    csiDriver:
      name: org.democratic-csi.truenas-nvmeof
      fsGroupPolicy: ReadWriteOnceWithFSType
    driver:
      existingConfigSecret: democratic-csi-nvmeof-config
      config:
        driver: freenas-api-nvmeof
    controller:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      driver:
        image:
          tag: v1.9.5
    node:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      driver:
        image:
          tag: v1.9.5
        nvmeDirMountEnabled: true
        nvmeDirHostPathType: DirectoryOrCreate
    storageClasses:
      - name: truenas-nvmeof
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
    volumeSnapshotClasses:
      - name: truenas-nvmeof-snap
        driver: org.democratic-csi.truenas-nvmeof
        deletionPolicy: Delete
        parameters:
          detachedSnapshots: "true"
