apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:sWVKBerssXmr2wyX8bIbfUao86mQfg9wX4n1VoKL5l1OhIHmNlCKFnDOwg12Wm6Kjke5SBWqr6eNZYVO7KkO7DLruiEzBMZGACQLERwo77ISHKhUaCqYtMY6WiQ2HYk43OPc1dr+uP8cmM6mFPm6z/17BDezLiedSc7j8YqqUm1k4C/U6Op7L6xB3sjlX/pKvxCGKOAshyakstv4Q2GbRPpWtb+FKR26euz42boY3ng+4SPz,iv:9dTWZ9yEJo+ed75Vj6jzySdBGVR8TBjlCHZxXJ3GPyA=,tag:UyhXYwF94eczE5cIWzM/FA==,type:str]
sops:
  age:
    - recipient: age1dc9236rsea7k8gtqttxfr832cz3s5k6rx37cqvuxe0432ud22yqsf9mhqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjQvZm1KenREUWFHUVRP
        d3dTVW4yZWEzaTZ1eVBlVlRuUlR2c1A4S1Z3Cnd4RlZNclh1ZWxGbnZHMjVGY3BH
        ZTcxQkNXWFR6dTF6QXBxeCtqUXUzL2sKLS0tIGdzSTAvM3daRVVLa1h0WFFNSGox
        VzZ4SlFSMUMxYWkyK281eHhIekJ6UVEKMj0vFQ7b95rD7VLWIva7Ddh6CSO/mGaZ
        JTL2KJfxZU4zCZoDHcSndfMTEzvjTae2OPhbccrYAQX/ebBFrw6GJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:19:56Z"
  mac: ENC[AES256_GCM,data:Pxc/YdvU4QrQpay6Z68EtSchwG7mZK1SPHTecg0MM7m+6P7UfqfO7Rj7AiKZAe6JG/Iv9STu+1qpqPk+hKkndzTCTiOOfEntkQfbeUa8usfnfZj30kn45R3iV+4aJnjkEPfYcLRmhMrzbDttZGAh889khRhbizNUFCnpvJ7TAZU=,iv:fYqTPCRZREs+ikK5rhA74Dk6jriVPSjuPNIOsljks+A=,tag:fvjH2pWcm+VJUloHkwD96A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
