apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Oy7ckgGQziWF3TL2bpMVCjBKbbD4YT6D3Zn8suwgkTZe6qcGaLF2IQ==,iv:rivy/tY+46fE9MMJBLhPA7cePJNk4cPMABCTnTV0/HA=,tag:X1hdkotEIn7wj9Glqs5Meg==,type:str]
sops:
  age:
    - recipient: age1dc9236rsea7k8gtqttxfr832cz3s5k6rx37cqvuxe0432ud22yqsf9mhqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOGFoeWNacGg4WENFUXJx
        YVVGaG1NWjQ2Q1RyV05kYzZLaTFsNWJxMzBjCkcyUGE2QjZCQmhHRGxDa2NjN3g3
        RWdKU3ZVM3h5b05zS3Nxdks5UGRFM3MKLS0tIDRPODBEbm9VUWUzMDJucm8yK0pu
        aEFRN1BWTWtFWjA2M0FpcmFydGRYL00K1xVfLBYRGG0L3hbsxkSxKFEgtRgGRL6f
        KCee/6R8vmg2v8IcS4OK+gk/Ip7noGdMwiGqvj404ghLtOXd/zAjvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T01:19:56Z"
  mac: ENC[AES256_GCM,data:NaNhj/+J2KnCvqP1v/gjXLyuuvF4M0aw33GqCK08KmVkvv5hlV5GZob2YFHaYs2XhxvZMTTWuG8+ZMDH6diAes9CCm4cMz62fyudr97hNtQXjahLx6BA4s78mXV7dnzD0rVPtB4SAIWG2qvZPJ+jeUMGBx4MyK57acGEfmjdZP8=,iv:k/KNOEMJPWvGeKsPk8Q6p14M+rPgy+d9evcLhBDNGgU=,tag:8QW81ZfdIrxH9HGEyY8AQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
