---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./database
  - ./default
  - ./external-secrets
  - ./flux-system
  - ./kube-system
  - ./media
  - ./network
  - ./observability
  - ./openebs-system
  - ./volsync-system
