---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-default
  namespace: kube-system
spec:
  description: Default config for Cilium-managed Gateways
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
  description: Default Cilium GatewayClass
